[wokwi]
version = 1
filesystem = ".pio/build/esp32-c3-devkitm-1/littlefs.bin"
firmware = ".pio/build/esp32-c3-devkitm-1/firmware.bin"
partitions = ".pio/build/esp32-c3-devkitm-1/partitions.bin"
debug = true
gdbServerPort = 3333